#!/bin/bash

set -e

output=lesswrong.$1
rm -f $output

time ebook-convert target/index.html $output \
    --input-encoding=utf-8 \
    --chapter=//h1 \
    --use-auto-toc \
    --title="Blog posts 2006-2010" \
    --authors="Eliezer Yudkowsky" \
    --language=en-US \
    --cover=cover.jpg \
    --max-toc-links=0 \
    --breadth-first


