#!/usr/bin/python

import instancemap

def tryencoding(encoding, c):
    try:
        decode = c.encode(encoding).decode("utf-8")
        return encoding, decode
    except Exception, e:
        #print encoding, "failed" #, e
        return None
    
for k, v in instancemap.instances.iteritems():
    suggestions = []
    if len(k) > 1:
        for encoding in "latin-1", "cp874":
            try:
                suggestions.append((encoding, 
                    k.encode(encoding).decode("utf-8")))
            except UnicodeEncodeError, e:
                pass
            except UnicodeDecodeError, e:
                pass
    print repr(k), suggestions
    for x in v:
        print "---- ", repr(x)
    print " ============================================ "


