xpath = "//div[@id=\'bodyContent\']//ul//li//a/@href"

def idxpath(spid):
    return "//span[@id=\"{0}\"]/parent::*/following-sibling::ul[1]//li//a[1]/@href".format(spid)

sequences = [
    ("Map and Territory",
        "http://wiki.lesswrong.com/wiki/Map_and_Territory_(sequence)",
        idxpath("Introductory_Posts_and_Essays")),
    ("Mysterious Answers to Mysterious Questions",
        "http://wiki.lesswrong.com/wiki/Mysterious_Answers_to_Mysterious_Questions",
        "//span[@id=\"Main_sequence\"]/parent::*/following-sibling::h5//a/@href"),

    ("Politics is the Mind-Killer",
        "http://wiki.lesswrong.com/wiki/Politics_is_the_Mind-Killer",
        idxpath("Blog_posts")),
    ("Death Spirals and the Cult Attractor",
        "http://wiki.lesswrong.com/wiki/Death_Spirals_and_the_Cult_Attractor",
        xpath),
    ("Seeing with Fresh Eyes",
        "http://wiki.lesswrong.com/wiki/Seeing_with_Fresh_Eyes",
        idxpath("Blog_posts")),
    ("Noticing Confusion",
        "http://wiki.lesswrong.com/wiki/How_To_Actually_Change_Your_Mind",
        idxpath("Noticing_Confusion")),
    ("Against Rationalization",
        "http://wiki.lesswrong.com/wiki/How_To_Actually_Change_Your_Mind",
        idxpath("Against_Rationalization")),
    ("Against Doublethink",
        "http://wiki.lesswrong.com/wiki/How_To_Actually_Change_Your_Mind",
        idxpath("Against_Doublethink")),
    ("Overly Convenient Excuses",
        "http://wiki.lesswrong.com/wiki/How_To_Actually_Change_Your_Mind",
        idxpath("Overly_Convenient_Excuses")),
    ("Letting Go",
        "http://wiki.lesswrong.com/wiki/How_To_Actually_Change_Your_Mind",
        idxpath("Letting_Go")),

    ("A Human's Guide to Words",
        "http://wiki.lesswrong.com/wiki/A_Human's_Guide_to_Words",
        xpath),
    ("Reductionism",
        "http://wiki.lesswrong.com/wiki/Reductionism_(sequence)",
        idxpath("Main_sequence")),
    ("Quantum Physics",
        "http://wiki.lesswrong.com/wiki/The_Quantum_Physics_Sequence",
        xpath),
    ("Metaethics",
        "http://wiki.lesswrong.com/wiki/Metaethics_sequence",
        idxpath("Blog_posts_.28in_primary_sequence.29")),
    ("Fun Theory",
        "http://wiki.lesswrong.com/wiki/The_Fun_Theory_Sequence",
        xpath),
    ("The Craft and the Community",
        "http://wiki.lesswrong.com/wiki/The_Craft_and_the_Community",
        xpath),
    ("Highly Advanced Epistemology 101 for Beginners",
        "http://wiki.lesswrong.com/wiki/Highly_Advanced_Epistemology_101_for_Beginners",
        xpath),

    ("Joy in the Merely Real",
        "http://wiki.lesswrong.com/wiki/Joy_in_the_Merely_Real",
        idxpath("Blog_Posts")),
    ("Zombies",
        "http://wiki.lesswrong.com/wiki/Zombies_(sequence)",
        xpath),
    ("Evolution",
        "http://wiki.lesswrong.com/wiki/Evolution",
        idxpath("Blog_posts_.28sequence.29")),
    ("Challenging the Difficult",
        "http://wiki.lesswrong.com/wiki/Challenging_the_Difficult",
        xpath),
    ("Yudkowsky's Coming of Age",
        "http://wiki.lesswrong.com/wiki/Yudkowsky's_Coming_of_Age",
        xpath),
]
